=== kevinzamoraa/CFGS-DAM/1-1er_Curso/LMSGI/PruebasEv/Examen_LM_2-parcial/mensajes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mensajes" type="mensaje"></xs:element>
    <xs:complexType name="mensaje">
        <xs:attribute name="tipo" use="required">
            <xs:simpleType>
                <xs:restriction>
                    <xs:enumeration value="salida"></xs:enumeration>
                    <xs:enumeration value="entrada"></xs:enumeration>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="de" ></xs:element>
    <xs:element name="para"></xs:element>
    <xs:element name="mensaje"></xs:element>
    <xs:element name="orden"></xs:element>
    <xs:element name="leido"></xs:element>


</xs:schema>

=== kevinzamoraa/CFGS-DAM/1-1er_Curso/LMSGI/PruebasEv/Examen_LM_2-parcial/mensajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<mensajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mensajes.xsd">
<mensaje tipo="entrada">
	<de>Juan</de>
	<para>María</para>
	<mensaje>Hola, ya he llegado</mensaje>
	<orden>1</orden>
	<leido/>
</mensaje>
<mensaje tipo="salida">
	<de>María</de>
	<para>Oscar</para>
	<para>Luisa</para>
	<mensaje>Juan ya he llegado</mensaje>
	<orden>2</orden>
</mensaje>
</mensajes>
